service: my-service
provider:
  name: aws
  runtime: nodejs4.3

custom:
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true

plugins:
  - serverless-dynamodb-local

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1